"""initial schema

Revision ID: 1a35e4e35ca6
Revises: 
Create Date: 2026-03-03 18:06:39.238740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a35e4e35ca6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sigle', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliations_id'), 'affiliations', ['id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('given_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=128), nullable=True),
    sa.Column('google_scholar_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_scholar_id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=32), nullable=False),
    sa.Column('core_rank', sa.String(length=16), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('wikicfp_series_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conferences_abbreviation'), 'conferences', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_conferences_id'), 'conferences', ['id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=64), nullable=True),
    sa.Column('scimago_id', sa.String(length=64), nullable=True),
    sa.Column('impact_factor', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rank', sa.String(length=16), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.create_table('research_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['research_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_groups_id'), 'research_groups', ['id'], unique=False)
    op.create_table('author_affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_affiliations_affiliation_id'), 'author_affiliations', ['affiliation_id'], unique=False)
    op.create_index(op.f('ix_author_affiliations_author_id'), 'author_affiliations', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_affiliations_id'), 'author_affiliations', ['id'], unique=False)
    op.create_table('conference_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('wikicfp_id', sa.String(length=64), nullable=True),
    sa.Column('abstract_deadline', sa.Date(), nullable=True),
    sa.Column('full_paper_deadline', sa.Date(), nullable=True),
    sa.Column('rebuttal_start', sa.Date(), nullable=True),
    sa.Column('rebuttal_end', sa.Date(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('camera_ready_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'year', name='uq_conference_edition')
    )
    op.create_index(op.f('ix_conference_editions_conference_id'), 'conference_editions', ['conference_id'], unique=False)
    op.create_index(op.f('ix_conference_editions_id'), 'conference_editions', ['id'], unique=False)
    op.create_table('journal_special_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_special_issues_id'), 'journal_special_issues', ['id'], unique=False)
    op.create_index(op.f('ix_journal_special_issues_journal_id'), 'journal_special_issues', ['journal_id'], unique=False)
    op.create_table('scholar_author_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('gs_entries', sa.Integer(), nullable=True),
    sa.Column('current_year_citations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholar_author_snapshots_author_id'), 'scholar_author_snapshots', ['author_id'], unique=False)
    op.create_index(op.f('ix_scholar_author_snapshots_date'), 'scholar_author_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_scholar_author_snapshots_id'), 'scholar_author_snapshots', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='grouprole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('paper_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'wip', 'submitted', 'under_review', 'major_revision', 'minor_revision', 'accepted', 'published', 'rejected', name='paperstatus'), nullable=False),
    sa.Column('overleaf_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('google_scholar_paper_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_projects_id'), 'paper_projects', ['id'], unique=False)
    op.create_table('starred_conference_editions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conference_edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_edition_id'], ['conference_editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'conference_edition_id')
    )
    op.create_table('paper_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_authors_author_id'), 'paper_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_paper_authors_id'), 'paper_authors', ['id'], unique=False)
    op.create_index(op.f('ix_paper_authors_paper_id'), 'paper_authors', ['paper_id'], unique=False)
    op.create_table('paper_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_comments_id'), 'paper_comments', ['id'], unique=False)
    op.create_index(op.f('ix_paper_comments_paper_id'), 'paper_comments', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_comments_user_id'), 'paper_comments', ['user_id'], unique=False)
    op.create_table('paper_conference_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('conference_edition_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn', name='submissionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['conference_edition_id'], ['conference_editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_conference_submissions_conference_edition_id'), 'paper_conference_submissions', ['conference_edition_id'], unique=False)
    op.create_index(op.f('ix_paper_conference_submissions_id'), 'paper_conference_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_conference_submissions_paper_id'), 'paper_conference_submissions', ['paper_id'], unique=False)
    op.create_table('paper_group_shares',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'group_id')
    )
    op.create_table('paper_journal_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('special_issue_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn', name='submissionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['special_issue_id'], ['journal_special_issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_journal_submissions_id'), 'paper_journal_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_journal_submissions_journal_id'), 'paper_journal_submissions', ['journal_id'], unique=False)
    op.create_index(op.f('ix_paper_journal_submissions_paper_id'), 'paper_journal_submissions', ['paper_id'], unique=False)
    op.create_table('scholar_paper_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('gs_paper_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('num_citations', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('year', sa.String(length=8), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('author_list', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholar_paper_snapshots_date'), 'scholar_paper_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_scholar_paper_snapshots_gs_paper_id'), 'scholar_paper_snapshots', ['gs_paper_id'], unique=False)
    op.create_index(op.f('ix_scholar_paper_snapshots_id'), 'scholar_paper_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_scholar_paper_snapshots_paper_id'), 'scholar_paper_snapshots', ['paper_id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='todostatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.create_index(op.f('ix_todo_items_paper_id'), 'todo_items', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_items_paper_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_scholar_paper_snapshots_paper_id'), table_name='scholar_paper_snapshots')
    op.drop_index(op.f('ix_scholar_paper_snapshots_id'), table_name='scholar_paper_snapshots')
    op.drop_index(op.f('ix_scholar_paper_snapshots_gs_paper_id'), table_name='scholar_paper_snapshots')
    op.drop_index(op.f('ix_scholar_paper_snapshots_date'), table_name='scholar_paper_snapshots')
    op.drop_table('scholar_paper_snapshots')
    op.drop_index(op.f('ix_paper_journal_submissions_paper_id'), table_name='paper_journal_submissions')
    op.drop_index(op.f('ix_paper_journal_submissions_journal_id'), table_name='paper_journal_submissions')
    op.drop_index(op.f('ix_paper_journal_submissions_id'), table_name='paper_journal_submissions')
    op.drop_table('paper_journal_submissions')
    op.drop_table('paper_group_shares')
    op.drop_index(op.f('ix_paper_conference_submissions_paper_id'), table_name='paper_conference_submissions')
    op.drop_index(op.f('ix_paper_conference_submissions_id'), table_name='paper_conference_submissions')
    op.drop_index(op.f('ix_paper_conference_submissions_conference_edition_id'), table_name='paper_conference_submissions')
    op.drop_table('paper_conference_submissions')
    op.drop_index(op.f('ix_paper_comments_user_id'), table_name='paper_comments')
    op.drop_index(op.f('ix_paper_comments_paper_id'), table_name='paper_comments')
    op.drop_index(op.f('ix_paper_comments_id'), table_name='paper_comments')
    op.drop_table('paper_comments')
    op.drop_index(op.f('ix_paper_authors_paper_id'), table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_id'), table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_author_id'), table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_table('starred_conference_editions')
    op.drop_index(op.f('ix_paper_projects_id'), table_name='paper_projects')
    op.drop_table('paper_projects')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scholar_author_snapshots_id'), table_name='scholar_author_snapshots')
    op.drop_index(op.f('ix_scholar_author_snapshots_date'), table_name='scholar_author_snapshots')
    op.drop_index(op.f('ix_scholar_author_snapshots_author_id'), table_name='scholar_author_snapshots')
    op.drop_table('scholar_author_snapshots')
    op.drop_index(op.f('ix_journal_special_issues_journal_id'), table_name='journal_special_issues')
    op.drop_index(op.f('ix_journal_special_issues_id'), table_name='journal_special_issues')
    op.drop_table('journal_special_issues')
    op.drop_index(op.f('ix_conference_editions_id'), table_name='conference_editions')
    op.drop_index(op.f('ix_conference_editions_conference_id'), table_name='conference_editions')
    op.drop_table('conference_editions')
    op.drop_index(op.f('ix_author_affiliations_id'), table_name='author_affiliations')
    op.drop_index(op.f('ix_author_affiliations_author_id'), table_name='author_affiliations')
    op.drop_index(op.f('ix_author_affiliations_affiliation_id'), table_name='author_affiliations')
    op.drop_table('author_affiliations')
    op.drop_index(op.f('ix_research_groups_id'), table_name='research_groups')
    op.drop_table('research_groups')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_conferences_id'), table_name='conferences')
    op.drop_index(op.f('ix_conferences_abbreviation'), table_name='conferences')
    op.drop_table('conferences')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_affiliations_id'), table_name='affiliations')
    op.drop_table('affiliations')
    # ### end Alembic commands ###
