"""add_conference_edition_dates

Revision ID: 7e6836c65cc3
Revises: 1a35e4e35ca6
Create Date: 2026-03-03 18:49:46.376814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6836c65cc3'
down_revision: Union[str, None] = '1a35e4e35ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference_editions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('conference_editions', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference_editions', 'end_date')
    op.drop_column('conference_editions', 'start_date')
    # ### end Alembic commands ###
