"""add_paper_resources_and_change_log

Revision ID: 892b23745c2e
Revises: 7e6836c65cc3
Create Date: 2026-03-04 08:40:38.839859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892b23745c2e'
down_revision: Union[str, None] = '7e6836c65cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('resource_type', sa.Enum('link', 'file', 'overleaf', 'github', name='paperresourcetype'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_resources_id'), 'paper_resources', ['id'], unique=False)
    op.create_index(op.f('ix_paper_resources_paper_id'), 'paper_resources', ['paper_id'], unique=False)
    op.create_table('paper_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('status_change', 'submitted_conference', 'submitted_journal', 'resource_added', 'resource_removed', 'note', name='papereventtype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('conference_edition_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('special_issue_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_edition_id'], ['conference_editions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['paper_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['special_issue_id'], ['journal_special_issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_change_logs_id'), 'paper_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_paper_change_logs_paper_id'), 'paper_change_logs', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_change_logs_paper_id'), table_name='paper_change_logs')
    op.drop_index(op.f('ix_paper_change_logs_id'), table_name='paper_change_logs')
    op.drop_table('paper_change_logs')
    op.drop_index(op.f('ix_paper_resources_paper_id'), table_name='paper_resources')
    op.drop_index(op.f('ix_paper_resources_id'), table_name='paper_resources')
    op.drop_table('paper_resources')
    # ### end Alembic commands ###
