"""add personal calendar events

Revision ID: abc8437c0982
Revises: 892b23745c2e
Create Date: 2026-03-04 18:32:56.612769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc8437c0982'
down_revision: Union[str, None] = '892b23745c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_calendar_events_id'), 'personal_calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_personal_calendar_events_user_id'), 'personal_calendar_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_calendar_events_user_id'), table_name='personal_calendar_events')
    op.drop_index(op.f('ix_personal_calendar_events_id'), table_name='personal_calendar_events')
    op.drop_table('personal_calendar_events')
    # ### end Alembic commands ###
